//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.25 at 09:56:24 AM MSK 
//


package rs3.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for departmentFromXsd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="departmentFromXsd">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="departmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="avgSalary" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="department_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="employeesList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "departmentFromXsd", propOrder = {
    "departmentName",
    "avgSalary",
    "departmentId",
    "employeesList"
})
public class DepartmentFromXsd {

    @XmlElement(required = true)
    protected String departmentName;
    protected double avgSalary;
    @XmlElement(name = "department_id")
    protected int departmentId;
    @XmlElement(required = true)
    protected String employeesList;

    /**
     * Gets the value of the departmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * Sets the value of the departmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentName(String value) {
        this.departmentName = value;
    }

    /**
     * Gets the value of the avgSalary property.
     * 
     */
    public double getAvgSalary() {
        return avgSalary;
    }

    /**
     * Sets the value of the avgSalary property.
     * 
     */
    public void setAvgSalary(double value) {
        this.avgSalary = value;
    }

    /**
     * Gets the value of the departmentId property.
     * 
     */
    public int getDepartmentId() {
        return departmentId;
    }

    /**
     * Sets the value of the departmentId property.
     * 
     */
    public void setDepartmentId(int value) {
        this.departmentId = value;
    }

    /**
     * Gets the value of the employeesList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeesList() {
        return employeesList;
    }

    /**
     * Sets the value of the employeesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeesList(String value) {
        this.employeesList = value;
    }

}
